------------------------------ TẠO DATABSE QUẢN LÝ HỌC SINH ------------------------------
CREATE DATABASE QLHS
ON
(
	NAME = QLHS_DATA,
	FILENAME = 'D:\QLHS.MDF',
	SIZE = 8,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2
)
LOG ON
(
	NAME = QLHS_LOG,
	FILENAME = 'D:\QLHS.LDF',
	SIZE = 8,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2
)

USE QLHS

CREATE TABLE LOGIN_TABLE
(
	USERNAME	VARCHAR(15),
	PASSWORD	VARCHAR(15),
	QUYEN		NVARCHAR(5),
	CONSTRAINT PK_LOGIN_TABLE PRIMARY KEY(USERNAME)
)

CREATE TABLE PHUHUYNH
(
	MAPH		CHAR(5), 
	HOTEN		NVARCHAR(255) NOT NULL,
	NGAYSINH	DATE,
	DIACHI		NVARCHAR(255),
	SODT		VARCHAR(10),
	QUANHE		NVARCHAR(10),
	GIOITINH	NVARCHAR(3) DEFAULT(N'NAM') CHECK(GIOITINH IN('NAM','NỮ')),
	CONSTRAINT PK_PHUHUYNH PRIMARY KEY(MAPH)
)

CREATE TABLE NAMHOC
(
	MANH	CHAR(5),
	MAHK	TINYINT,
	CONSTRAINT PK_NAMHOC PRIMARY KEY(MANH, MAHK)
)

CREATE TABLE LOPHOC
(
	MALOP	CHAR(5),
	TENLOP	NVARCHAR(15)	NOT NULL,
	SISO	TINYINT CHECK(SISO >= 0 AND SISO <=50), -- UPDATE THEO COUNT HỌC SINH(GIÁO VIÊN)
	GVCN	CHAR(5) NOT NULL,
	MANH	CHAR(5),
	MAHK	TINYINT,
	CONSTRAINT PK_LOPHOC PRIMARY KEY(MALOP)
)

CREATE TABLE HOCSINH
(
	MAHS		CHAR(5), 
	HOTEN		NVARCHAR(255) NOT NULL,
	NGAYSINH	DATE,
	DIACHI		NVARCHAR(255),
	SODT		VARCHAR(10),
	MALOP		CHAR(5)	NOT NULL,
	MAPH		CHAR(5),
	GIOITINH	NVARCHAR(3),
	USERNAME	VARCHAR(15)
	CONSTRAINT PK_HOCSINH PRIMARY KEY(MAHS)
)

CREATE TABLE TOGV
(
	MATOGV	CHAR(5),
	TRUONGTOGV CHAR(5),
	TENTOGV	NVARCHAR(255),
	CONSTRAINT PK_TOGV PRIMARY KEY(MATOGV)
)

CREATE TABLE GIAOVIEN
(
	MAGV		CHAR(5), 
	HOTEN		NVARCHAR(255) NOT NULL,
	NGAYSINH	DATE,
	QUEQUAN		NVARCHAR(255),
	SODT		VARCHAR(10),
	EMAIL		VARCHAR(255) CHECK(EMAIL LIKE '%@%' AND EMAIL NOT LIKE '% %') UNIQUE,
	GIOITINH	NVARCHAR(3),
	MONGD		NVARCHAR(30),
	MATOGV		CHAR(5),
	USERNAME	VARCHAR(15)
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY(MAGV)
)

CREATE TABLE BANGDIEM
(
	MAHS	CHAR(5),
	MANH	CHAR(5),
	MAHK	TINYINT,
	MAMH	CHAR(5),	
	TOAN	DEC(2,2),
	NGUVAN	DEC(2,2),
	NGOAINGU DEC(2,2),
	VATLY	DEC(2,2),
	HOAHOC	DEC(2,2),
	SINHOC	DEC(2,2),
	GDCD	DEC(2,2),
	DIALY	DEC(2,2),
	LICHSU	DEC(2,2),
	DTB		DEC(2,2),
	CONSTRAINT PK_BANGDIEM PRIMARY KEY(MAHS, MAHK, MANH)
)

CREATE TABLE HANHKIEM
(
	MAHS	CHAR(5),
	MANH	CHAR(5),
	MAHK	TINYINT,
	LOAIHK	NVARCHAR(30),
	CONSTRAINT PK_HANHKIEM PRIMARY KEY(MAHS, MANH, MAHK)
)

CREATE TABLE THUNGAN
(
	MAHS CHAR(5),
	MANH CHAR(5),
	MAHK TINYINT,	
	SOTIEN_HP FLOAT,
	TINHTRANG_HP NVARCHAR(15),
	NGAYDONG_HP DATE,
	SOTIEN_BHYT FLOAT,
	TINHTRANG_BHYT NVARCHAR(15),
	NGAYDONG_BHYT DATE,	
	CONSTRAINT PK_THUNGAN PRIMARY KEY(MAHS, MAHK, MANH)
)

-- KHÓA NGOẠI
ALTER TABLE HOCSINH
ADD CONSTRAINT FK_HOCSINH_PHUHUYNH FOREIGN KEY (MAPH) REFERENCES PHUHUYNH(MAPH),
	CONSTRAINT FK_HOCSINH_LOPHOC FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP),
	CONSTRAINT FK_HOCSINH_LOGIN_TABLE FOREIGN KEY(USERNAME) REFERENCES LOGIN_TABLE(USERNAME)

ALTER TABLE TOGV
ADD CONSTRAINT FK_TOGV_GIAOVIEN FOREIGN KEY (TRUONGTOGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_TOGV FOREIGN KEY (MATOGV) REFERENCES TOGV(MATOGV),
	CONSTRAINT FK_GIAOVIEN_LOGIN_TABLE FOREIGN KEY(USERNAME) REFERENCES LOGIN_TABLE(USERNAME)

ALTER TABLE LOPHOC
ADD	CONSTRAINT FK_LOPHOC_NAMHOC FOREIGN KEY(MANH, MAHK) REFERENCES NAMHOC(MANH, MAHK),
	CONSTRAINT FK_LOPHOC_GIAOVIEN FOREIGN KEY(GVCN) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCSINH FOREIGN KEY(MAHS) REFERENCES HOCSINH(MAHS),
	CONSTRAINT FK_BANGDIEM_NAMHOC FOREIGN KEY(MANH, MAHK) REFERENCES NAMHOC(MANH, MAHK)	

ALTER TABLE THUNGAN
ADD CONSTRAINT FK_THUNGAN_HOCSINH FOREIGN KEY(MAHS) REFERENCES HOCSINH(MAHS),
	CONSTRAINT FK_THUNGAN_NAMHOC FOREIGN KEY(MANH, MAHK) REFERENCES NAMHOC(MANH, MAHK)

ALTER TABLE HANHKIEM
ADD CONSTRAINT FK_HANHKIEM_HOCSINH FOREIGN KEY(MAHS) REFERENCES HOCSINH(MAHS),
	CONSTRAINT FK_HANHKIEM_NAMHOC FOREIGN KEY(MANH, MAHK) REFERENCES NAMHOC(MANH, MAHK)

-- 1 Số thông tin ban đầu 
INSERT INTO LOGIN_TABLE VALUES
('admin', 'admin', 'AD'),
('GV001', 'gv001', 'GV'),
('GV002', 'gv002', 'GV'),
('GV003', 'gv003', 'GV')

INSERT INTO GIAOVIEN(MAGV, HOTEN, NGAYSINH, QUEQUAN, EMAIL, SODT, GIOITINH, MATOGV, USERNAME, MONGD) VALUES 
('GV001', N'Nguyễn An', '1990-05-12', N'Long Xuyên, An Giang', 'nguyenan@gmail.com', '0934235434', N'Nam', null, 'GV001', N'Địa lý'),
('GV002', N'Nguyễn Văn Đạt', '1994-03-22', N'Long Xuyên, An Giang', 'nguyenvandat@gmail.com', '0325463214', N'Nữ', null, 'GV002', N'Toán'),
('GV003', N'Lý Kim Hương', '1991-05-11', N'Long Xuyên, An Giang', 'lykimhuong@gmail.com', '0325465549', N'Nam', null, 'GV003', N'GDQP')

--	CREATE STORE PROCDUCE
CREATE PROC sp_checkLogin_LOGIN_TABLE
	@tenTK VARCHAR(15),
	@matkhau VARCHAR(15)
AS
BEGIN
	SELECT * FROM QLHS.dbo.LOGIN_TABLE WHERE USERNAME = @tenTK AND PASSWORD = @matkhau
END
GO

CREATE PROC sp_Select_NamHoc_ByMaHK
AS
BEGIN 
	SELECT * FROM QLHS.dbo.NAMHOC WHERE MAHK = 1
END

SELECT * FROM NAMHOC WHERE MAHK = 1
